name: Docker
# 触发条件为 push
on:
  push:
    branches:
      - feature/docker
    # 修改文件范围, 不在范围内不触发
    # paths:
    #   - '.github/workflows/**'
    #   - '__test__/**'
    #   - 'src/**'
# 任务
jobs:
  docker-deploy:
    # 运行的环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      - uses: actions/checkout@v2 # git pull
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # 1.登录docker; 2. 执行Dockerfile,生成镜像；3.推送到镜像仓库 Docker hub
      # - name: 打包镜像, 上传 Docker Hub
      #   run: |
      #     echo "开始登录 Docker Hub"
      #     git checkout feature/docker
      #     docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      #     docker build --no-cache -t="verneyzhou/githook-vite-test:latest" . 
      #     docker push verneyzhou/githook-vite-test:latest
      
      - name: 打包镜像, 上传 阿里云 Docker Registry
        run: |
          echo "开始登录 Docker Hub"
          git checkout feature/docker
          docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          docker build --no-cache -t="verneyzhou/githook-vite-test:latest" . 
          echo "开始登录 阿里云 Docker Registry"
          docker login --username=${{ secrets.DOCKER_ALI_REGISTRY_USERNAME }} registry.cn-beijing.aliyuncs.com -p ${{ secrets.DOCKER_ALI_REGISTRY_PASSWORD }}
          docker tag verneyzhou/githook-vite-test:latest registry.cn-beijing.aliyuncs.com/zhou_aliyun_image/githook-vite-test:v1.0
          docker push registry.cn-beijing.aliyuncs.com/zhou_aliyun_image/githook-vite-test:v1.0

      # - name: 登录服务器, 执行脚本
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.ALIYUN_HOST }} # 远程服务器ip地址
      #     username: root
      #     password: ${{ secrets.ALIYUN_ROOT_PWD }}  # 用户密码
      #     # 执行脚本
      #     script: |
      #       ./docker-deploy.sh

      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.1
        with:
          HOST: ${{ secrets.ALIYUN_HOST }}
          PORT: 22 
          USER: root
          PRIVATE_SSH_KEY: ${{ secrets.ALIYUN_ECS_KEY }}
          # chmod 添加可执行权限 => 执行
          # COMMAND: pwd & ls & chmod +x ./docker-deploy.sh & sh ./docker-deploy.sh ${{ secrets.DOCKER_REGISTRY_USERNAME }} ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          COMMAND: pwd & ls & chmod +x ./docker-deploy.sh & sh ./docker-deploy.sh ${{ secrets.DOCKER_ALI_REGISTRY_USERNAME }} ${{ secrets.DOCKER_ALI_REGISTRY_PASSWORD }}

